Added install.sh functions, halfway fixed m_macchanger

diff --git a/bin/m_macchanger b/bin/m_macchanger
--- a/bin/m_macchanger
+++ b/bin/m_macchanger
@@ -2,14 +2,42 @@
 
 TITLE="TiMac - A Time based MAC-Adress Changer"
 
-if [ "$#" -ne 3 ]
-    then
-	echo "Syntax: TiMac [hours] [minutes] [seconds]"
-    else
-	wifi = ip r show | grep " src " | cut -d " " -f 3,12
-  sudo ifconfig $wifi down
-	sudo macchanger --random $wifi
-  sudo ifconfig $wifi up
-	echo "Next MAC-Adress is genereated in ($1):($2):($3)"
-	sudo macchanger --random $wifi | at now + $1 hours + $2 minutes + $3 seconds
+if [[ $UID != 0 ]]; then
+    echo "Please run this script with sudo:"
+    exit 1
+  else
+    if [ "$#" -ne 3 ]
+        then
+    	    echo "Syntax: TiMac [hours] [minutes] [seconds]"
+          exit 1
+        else
+          echo "[OK] Starting TiMAC ..."
+          #str="macchanger --random $wifi"
+        	wifi=$(ip r show | grep " src " | cut -d " " -f 3,12)
+          if [ ! -z $wifi]; then
+            while true
+            do
+              time = 'echo "$1+$2*60+$3*360" | bc'
+              echo time
+              sleep time
+
+              clear
+              printf "[OK] Wifi Interface: $wifi\n"
+              sudo ifconfig $wifi down
+              printf "[OK] $wifi down\n"
+            	sudo macchanger --random $wifi
+              sudo ifconfig $wifi up
+              printf "[OK] $wifi up\n"
+              # time in seconds
+              time = 'echo "$1+$2*60+$3*360" | bc'
+
+              sleep time
+            done
+            #TODO Implement crontab
+          	#echo "[INFO] Next MAC-Adress is genereated in ($1):($2):($3)"
+          else
+            printf "[ERR] Did not get wifi-interface. Mission abort"
+            exit -1
+          fi
+     fi
 fi
